{% set name = "papillon" %}
{% set version = "0.2.0" %}
{% set sha256 = "d461f6742e7c39d98a2eaa183417dcf1e728e254be59cad14e8455a36bd339a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1003
  skip: True  # [py<35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - pandas >=0.17.1
    - seaborn >=0.8.1

test:
  imports:
    - papillon

about:
  home: https://github.com/domenico-somma/Papillon/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'A Python module to read and plot cuffdiff/Galaxy RNA-seq data'

  doc_url: https://github.com/domenico-somma/Papillon/wiki/Manual
  dev_url: https://github.com/domenico-somma/Papillon

extra:
  recipe-maintainers:
    - domenico-somma
