appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UJre7OXiY4YXOeM/vUyBFmOLBZtn1f5flw9IgzpPOroSJKfxv9chFM4LQT5NyxYMi5A/lb2D9/Ny+PCHU7ftDxn1DyJ4LzA46oX/rhbp9kWrVaWV6kmtGO2ac+wHR/Y72ak9jv8sEeeQSmAhZDVv80UWSXfGNWrhrBV71OTIbRAF3SwoBsHa8NnzZsjIUnlhDEMd4y4G6NOYo++0ryO44uXLAC1lnwlkYhSG3eoI+D3RFpWc2by4aTrrrFq+qi1VPfHzpmGsXpA/OvGnIdLv8GBNhvW1QRsOufLPKwCVg51Yn/K/SwwsplIW121GgRqW3jVdY1/kpNOjBYaM4W3A85V77MRe+DeXL9EQYMqkPayv21gNYHsWdg9n9qyO1vALgeYhAYw71BOI4VNLmphLgqx08bOCD5Sbn6UBipoZT+n4AR2wu3Gea9liFSpLt45MQhlzGUQ4i3UmS/pOHVF7UFe4oqdpVMo+U6UUBnzBVpVpypmmQfntI8ZFMvujX6/NZ1u+cXdiXmnG3gmKfsYUlVBkxEzUyBIJEPpfohcSFeFOVGXbt8lFhYlRogpF5ihuj81GiOpg8NScATAIscy1lUTZTqMjnz7Q4qemu65ZKw4nB5i5bMLvxFk+vy0gzIYwGdSSvYiXJgXRznJTRTTD5OGgK0MTyplfk3egTdYvWlE=}
