travis:
  secure:
    BINSTAR_TOKEN: QNctnKFX0gA7IIJGqECETi2MssDD0c0c3i83Y01E1Zw0hAYHU+b35MKRiEO7cESv63AIK4lGTxe+a5mq7TKwe6kqaI6MJp6HXorZLKYRsX2+hFDy9REMQ5z8R6hIGJ77J0Bvu3JJRQobMQEDzL6jv/6nQ1EVw0D/MkE0H5vL5z9BZu9LnSLELuyONu05gI0pUezByVW6JpxlU/Q96h8PNT4krkzY6V0khcjPXOnGjOvusKoScP2taDztmyJ2Oj++8w19qjm9UgWWE0h4mIICpWYzf1DXqUt5VJLnVwWDZAxZn1A2TlM1sCetJeDo7dGYGChyASeXFfyu1o9K081MJvCSz7A+2Y+I/BbWNr/nGcehDR1fWc34QqIH4kejHrQCJF5DKT7tkHFDVM1deq1ROxA/NCQiCGJCX2Ti5J5EYIWrOVALDPqefdhzpOVIJxeyD1Lz+IJLjV+yKUPN3ax6Sj6uFIxieC8fYU6dYSrtbxU9Ez11o+wBD4T05ISCnpF5Cc8zcvuVHNLyBRM7FTQglMc0V8+hgKV0GFfATslSFuK8x9mgmmemGBe1UmD5VLhr+Z7CSznJy5XppShoZAwwDb15zM7u8nJgH0GZzor2pk6/lnRacwbLUtqK8JPM1q+uX5unioye23i8/UIZy5988JC7VnHlV03O692RuYt8t0k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
